=== uniwue-it4all/py_prog_corrector/unit_test_test_data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/TestData",
  "definitions": {
    "TestData": {
      "type": "object",
      "properties": {
        "folderName": {"type": "string"},
        "filename": {"type": "string"},
        "testFilename": {"type": "string"},
        "testConfigs": {
          "type": "array",
          "items": {"$ref": "#/definitions/TestConfig"}
        }
      },
      "required": ["folderName", "filename", "testFilename", "testConfigs"],
      "additionalProperties": false
    },
    "TestConfig": {
      "type": "object",
      "properties": {
        "id": {"type": "number"},
        "shouldFail": {"type": "boolean"},
        "description": {"type": "string"},
        "file": {}
      },
      "required": ["id", "shouldFail", "description"],
      "additionalProperties": false
    }
  }
}

=== uniwue-it4all/py_prog_corrector/circle/unit_test_data/unit_test_test_data.json
{
  "folderName": "circle",
  "filename": "circle",
  "testFilename": "test_circle",
  "testConfigs": [
    {
      "id": 0,
      "shouldFail": false,
      "description": "Musterlösung..."
    },
    {
      "id": 1,
      "shouldFail": true,
      "description": "Die X-Koordinate sollte eine Ganz- oder Fließkommazahl sein."
    },
    {
      "id": 3,
      "shouldFail": true,
      "description": "Der Wert des Konstruktorarguments 'center_x' sollte unter dem selben Namen als Argument zugänglich sein."
    },
    {
      "id": 4,
      "shouldFail": true,
      "description": "Die Y-Koordinate sollte eine Ganz- oder Fließkommazahl sein."
    },
    {
      "id": 5,
      "shouldFail": true,
      "description": "Der Wert des Konstruktorarguments 'center_y' sollte unter dem selben Namen als Argument zugänglich sein."
    },
    {
      "id": 6,
      "shouldFail": true,
      "description": "Der Radius sollte eine Ganz- oder Fließkommazahl sein."
    },
    {
      "id": 7,
      "shouldFail": true,
      "description": "Der Radius sollte größer oder gleich 0 sein."
    },
    {
      "id": 8,
      "shouldFail": true,
      "description": "Der Wert des Konstruktorarguments 'radius' sollte unter dem selben Namen als Argument zugänglich sein."
    },
    {
      "id": 5,
      "shouldFail": true,
      "description": "Die Fläche des Kreises sollte richtig berechnet werden."
    }
  ]
}

=== uniwue-it4all/py_prog_corrector/pysql/unit_test_data/unit_test_test_data.json
{
  "folderName": "pysql",
  "filename": "table",
  "testFilename": "test_table",
  "testConfigs": [
    {
      "id": 0,
      "shouldFail": false,
      "description": "Diese Implementierung ist korrekt und sollte alle Tests bestehen."
    },
    {
      "id": 1,
      "shouldFail": true,
      "description": "Es soll überprüft werden, ob die eingegebene Liste die gleiche Länge wie die Tabellenreihen hat."
    },
    {
      "id": 2,
      "shouldFail": true,
      "description": "Es soll überprüft werden, ob der Inhalt der eingegebenen Liste die gleichen Datentypen hat wie die Anfangsdaten."
    },
    {
      "id": 3,
      "shouldFail": true,
      "description": "Die Funktion sollte bei Erfolg True ausgeben."
    },
    {
      "id": 4,
      "shouldFail": true,
      "description": "Die letzte Zeile der Tabelle muss der angefügten Zeile entsprechen."
    },
    {
      "id": 5,
      "shouldFail": true,
      "description": "Die neue Anzahl an Zeilen muss um genau 1 höher sein."
    },
    {
      "id": 6,
      "shouldFail": true,
      "description": "Zahlen in der neuen Zeile sollen automatisch von Strings zu floats konvertiert werden."
    }
  ]
}

=== uniwue-it4all/py_prog_corrector/ggt/unit_test_data/unit_test_test_data.json
{
  "folderName": "ggt",
  "filename": "ggt",
  "testFilename": "test_ggt",
  "testConfigs": [
    {
      "id": 0,
      "shouldFail": false,
      "description": ""
    },
    {
      "id": 1,
      "shouldFail": true,
      "description": ""
    },
    {
      "id": 2,
      "shouldFail": true,
      "description": ""
    },
    {
      "id": 3,
      "shouldFail": true,
      "description": ""
    },
    {
      "id": 4,
      "shouldFail": true,
      "description": ""
    },
    {
      "id": 5,
      "shouldFail": true,
      "description": ""
    },
    {
      "id": 6,
      "shouldFail": true,
      "description": ""
    },
    {
      "id": 7,
      "shouldFail": true,
      "description": ""
    },
    {
      "id": 8,
      "shouldFail": true,
      "description": ""
    }
  ]
}

=== uniwue-it4all/py_prog_corrector/factorial/unit_test_test_data.json
{
  "folderName": "factorial",
  "filename": "factorial",
  "testFilename": "test_factorial",
  "testConfigs": [
    {
      "id": 0,
      "shouldFail": false,
      "description": "Diese Implementierung ist korrekt und sollte alle Tests bestehen."
    },
    {
      "id": 1,
      "shouldFail": true,
      "description": "Es soll überprüft werden, ob die Eingabe eine Ganzzahl ist."
    },
    {
      "id": 2,
      "shouldFail": true,
      "description": "Es soll überprüft werden, ob die Eingabe größer oder gleich 0 ist."
    },
    {
      "id": 3,
      "shouldFail": true,
      "description": "Es soll überprüft werden, ob die Funktion das richtige Resultat liefert."
    }
  ]
}
